### ISSUE TITLE
Support Request: Environment Setup and Configuration Guidance

### ISSUE THREAD

**Issue by IemProg** [kcolemangt/llm-router#1]
Hi,

Thanks a lot for the project !! 

Could you please provide the instructions to install with Cursor on mac ?

Best,

**Comment by kcolemangt** [comment]
> Hi,
> 
> Thanks a lot for the project !!
> 
> Could you please provide the instructions to install with Cursor on mac ?
> 
> Best,

Hi @IemProg,

Thank you for reaching out and for your interest in the project!

For installation instructions, you can refer to the [Getting Started](https://github.com/kcolemangt/llm-router?tab=readme-ov-file#getting-started) section in the README. Additionally, there's a detailed guide on [macOS Permissions](https://github.com/kcolemangt/llm-router?tab=readme-ov-file#macos-permissions) that might be helpful. Could you please check if these cover what you need? If something isn't clear or doesn't work, let me know!

**Comment by IemProg** [comment]
Thanks for the quick reply.

The issue i'm facing is with respect to the first instruction: 
`OPENAI_API_KEY=<YOUR_OPENAI_KEY> ./llm-router-darwin-arm64.`

It does not run on my Mac OS. I'm getting this error: bash: ./llm-router: is a directory.

I have included my API key in the command.
Thanks

**Comment by kcolemangt** [comment]
> Thanks for the quick reply.
> 
> The issue i'm facing is with respect to the first instruction: `OPENAI_API_KEY=<YOUR_OPENAI_KEY> ./llm-router-darwin-arm64.`
> 
> It does not run on my Mac OS. I'm getting this error: bash: ./llm-router: is a directory.
> 
> I have included my API key in the command. Thanks

Hi @IemProg,

Thank you for the update, and sorry for the confusion! Based on your description, it sounds like you may need to build the application from the source. Since you're encountering a directory issue, here’s how to proceed:

1. **Navigate to the Directory**: First, ensure you are in the directory containing the source code.
2. **Build the Application**: Follow the instructions in the README under [Method 5: Build from Source](https://github.com/kcolemangt/llm-router/blob/main/README.md#method-5-build-from-source).

**Comment by IemProg** [comment]
Thanks for the support. 
Indeed, I created the app form scratch using Go. Now, i'm getting this error, when executing the following command:
`./build/llm-router-local`

```
{"level":"warn","ts":1715179490.887719,"caller":"config/config.go:33","msg":"Config file not found, using default configuration","file":"config.json"}
{"level":"fatal","ts":1715179490.887841,"caller":"config/config.go:51","msg":"API key environment variable not set","variable":"OPENAI_API_KEY","stacktrace":"github.com/kcolemangt/llm-router/config.LoadConfig
```

Thanks a lot for the help.

**Comment by kcolemangt** [comment]
Hi @IemProg,

Great to hear you've made progress! The message you're seeing now indicates that the `OPENAI_API_KEY` environment variable hasn't been set. This is necessary for llm-router to authenticate your requests. Here's how to set it up and get everything running:

1. **Set the Environment Variable**: Before running llm-router, set the `OPENAI_API_KEY` in your terminal. Replace `<YOUR_OPENAI_KEY>` with your actual OpenAI API key (the same one you set in Cursor):
   ```sh
   OPENAI_API_KEY=<YOUR_OPENAI_KEY> ./build/llm-router-local
   ```

2. **Start ngrok**: Open a new terminal window and start ngrok to create a public HTTPS endpoint:
   ```sh
   ngrok http 11411
   ```

3. **Configure Cursor**: Ensure that Cursor's model settings `Override OpenAI Base URL` is pointed to your ngrok URL, appended with `/v1` (e.g., `https://xxxx.ngrok-free.app/v1`).

With these steps, Cursor should route your requests through ngrok to llm-router, which will handle forwarding them to the appropriate backend, like Ollama.

Let me know if you encounter any more issues or have further questions!

**Comment by IemProg** [comment]
Thanks a lot for your support ! 
Can you please provide the path to the Cursor's model settings in order to avoiride the OpenAI URL ?
I'm using Cursor on Mac.

Many thanks,

**Comment by kcolemangt** [comment]
To override the OpenAI URL in Cursor, go to Cursor AI settings, select the 'Models' section, and locate the 'Override OpenAI Base URL' field directly below where you enter your OpenAI API key.

**Comment by kcolemangt** [comment]
Hi @IemProg,

I hope the instructions resolved your issue. I'm curious to hear about your experience so far. Are there any particular models or providers you're finding useful or enjoyable through the llm-router setup?

If you have any further questions, please feel free to reach out. If I don't hear back from you within 48 hours, I'll assume all is well and close this issue.

**Comment by IemProg** [comment]
Hi,

I couldn't make it work properly. My objective is to connect it to Ollama in order to use Llama 3 model.

But I don't what's missing ? How can we add Ollama to cursor API models ?

If you can provide us with a detailed instructions about connecting to Ollama that would be great.

Thanks a lot

**Comment by kcolemangt** [comment]
Hi @IemProg,

Let's clarify a few things to ensure everything is set up correctly:

1. Do you have ngrok, llm-router, and Ollama running?
2. Is the ngrok URL set as the Override OpenAI Base URL in Cursor?
3. Do you have your OpenAI API key set?
4. Do you have the model set?

If something isn’t working, what’s the specific error message you’re seeing?

**Comment by IemProg** [comment]
Hi @kcolemangt ,

I did setup all the instructions above (Step 1 - Step 4). I'm not getting an error but just a warning of type :

> {"level":"warn","ts":1715787162.090896,"caller":"config/config.go:33","msg":"Config file not found, using default configuration","file":"config.json"}

I want to use ollama local model (Llama3), instead of OpenAI models, so how can I add Ollama connection in the Cursor (is it possible to add it to the list of cursor models) ?

Thanks a lot.

**Comment by kcolemangt** [comment]
Have you tried adding a model called `ollama/llama3` in Cursor? This should forward your requests to the Llama3 model on Ollama.

**Comment by IemProg** [comment]
Hi @kcolemangt,

Yes, it didn't work for me.

I'm getting an error of type: "INVALID API KEY", when I try to prompt the model (ollama/llama3-instruct). Although, the API key from OpenAI is valid, I use it for other applications.

Also, when I try to check if the API Key is valid in the settings of Cursor, I get this error: 

![Grok](https://github.com/kcolemangt/llm-router/assets/29262325/6ac1c270-4a87-477d-b6cc-d85874319cad)


Executing the command displayed in the figure, the output is: "Invalid or missing API key".
Any ideas what's wrong ?

This are the logs of the ngrok:
```
HTTP Requests
-------------

OPTIONS /v1/chat/completions   401 Unauthorized
POST    /v1/chat/completions   401 Unauthorized
OPTIONS /v1/chat/completions   401 Unauthorized
POST    /v1/chat/completions   401 Unauthorized
OPTIONS /v1/models             401 Unauthorized
```

Thanks a lot,

**Comment by kcolemangt** [comment]
The issue seems to be with the API key configuration. When launching llm-router, make sure you're using the same OpenAI API key that you’ve set in Cursor. You can do this by setting the environment variable before starting llm-router:

```sh
OPENAI_API_KEY=<YOUR_OPENAI_KEY> ./build/llm-router-local
```

Replace `<YOUR_OPENAI_KEY>` with the same OpenAI API key you use in Cursor.

**Comment by suvojit-0x55aa** [comment]
Where is the config.json file located ?
