### ISSUE TITLE
Is ngrok still local?

### ISSUE THREAD

**Issue by neuhaus** [kcolemangt/llm-router#3]
I'm not familiar with ngrok, does it mean that all my data for the local LLM will be sent via ngrok's servers? 
Does it make my local LLM available to the world, lowering my security?

How do i use llm-router to run cursor with a local LLM without ngrok?

**Comment by kcolemangt** [comment]
> I'm not familiar with ngrok, does it mean that all my data for the local LLM will be sent via ngrok's servers? 

> How do i use llm-router to run cursor with a local LLM without ngrok?

Cursor requires a public HTTPS endpoint. Options include managing your own DDNS, hosting Ollama & llm-router on a public web server, or other app hosting methods. Ngrok is a quick solution mentioned in the [Ollama FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-use-ollama-with-ngrok).

> Does it make my local LLM available to the world, lowering my security?

While Cursor needs a public endpoint, your API key prevents unauthorized access to your LLM.

**Comment by taoeffect** [comment]
Hmm... this doesn't seem like a local (offline) solution then.

You could get it working though by having a local DNS entry for a URL and serving it via HTTPS using e.g. https://github.com/FiloSottile/mkcert

**Comment by kcolemangt** [comment]
> Hmm... this doesn't seem like a local (offline) solution then.
> 
> You could get it working though by having a local DNS entry for a URL and serving it via HTTPS using e.g. https://github.com/FiloSottile/mkcert

This won't work if Cursor still requires a publicly accessible HTTPS endpoint, as their servers needed to call your inference endpoint directly (at least previously). If you get it working with just local DNS and certificates, please let me know - that would indicate Cursor has changed how they handle inference requests.​​​​​​​​​​​​​​​​

**Comment by taoeffect** [comment]
> This won't work if Cursor still requires a publicly accessible HTTPS endpoint

You would modify `/etc/hosts` (for example) to redirect your endpoint URL to localhost. Cursor will think it's connecting to the outside world but it's just connecting locally.

It will probably work, give it a try. If I ever decide I need Cursor enough I might try this myself, but right now [Zed](https://zed.dev/) is working great with local LLMs.
