### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by Intiiii** [kcolemangt/llm-router#4]
Hi, I can't really get it to work... Everytime I try, cursor gives the error: 
(status code 0)
TypeError: Failed to fetch,

and the router says:
Starting server on :11411
{"level":"warn","ts":1729099580.0293329,"caller":"handler/handler.go:23","msg":"Invalid or missing API key","receivedAuthHeader":"","expectedAuthHeader":"****** ******"}

and ngrok says:
19:26:20.029 CESTOPTIONS /v1/chat/completions   401 Unauthorized.

when using ollama, do you need an openai api key or do u use ollama instead when running $env:OPENAI_API_KEY="<OPENAPI_KEY>"; .\llm-router-windows-amd64.exe

**Comment by kcolemangt** [comment]
You're close! To resolve the "Invalid or missing API key" error:

1. Set an OpenAI API Key in Cursor's model settings.
2. Let Cursor verify the key.
3. Change the endpoint to your llm-router ngrok URL.
4. Use the same API key when launching llm-router.

This should complete your setup.

**Comment by krmao** [comment]
> 您已经接近成功！要解决“API 密钥无效或缺失”错误，请执行以下操作：
> 
> 1. 在 Cursor 的模型设置中设置 OpenAI API 密钥。
> 2. 让 Cursor 验证密钥。
> 3. 将端点更改为您的 llm-router ngrok URL。
> 4. 启动 llm-router 时使用相同的 API 密钥。
> 
> 这应该完成了您的设置。


means must be have a correct openai api key first?

<img width="1787" alt="image" src="https://github.com/user-attachments/assets/bc0f751b-ac51-4544-85a5-e022f5deb687" />

**Comment by kcolemangt** [comment]
@krmao  fixed in latest version
